services:
  wud:
    image: getwud/wud:main
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Potrebné na sledovanie ostatných kontajnerov
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 3010:3000
    environment:
      - WUD_WATCHER_LOCAL_CRON=0 0 6 * * *
      - WUD_WATCHER_LOCAL_WATCHALL=true
      - WUD_REGISTRY_HUB_PUBLIC_LOGIN=${DOCKERHUB_USER}
      - WUD_REGISTRY_HUB_PUBLIC_TOKEN=${DOCKERHUB_TOKEN}
    restart: always
networks: {}
