global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'zabbix-monitor'
    cluster: 'docker-compose'

alerting:
  alertmanagers:
    - api_version: v2
      static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alerts.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090'] # Zmenené z localhost na názov služby

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'zabbix-exporter'
    scrape_interval: 30s
    static_configs:
      - targets: ['zabbix-exporter:9285']

  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'zabbix-servers'
    scrape_interval: 60s
    metrics_path: /metrics
    static_configs:
      - targets: ['zabbix-exporter:9285']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '(server_up|linux_.*|windows_.*)'
        action: keep
  - job_name: "windows-servers"
    scrape_interval: 15s
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/targets.json
